#! /bin/sh

BSPWM_DIR=$HOME/.config/bspwm/
SCRIPTS_DIR=$HOME/.config/bspwm/scripts/
export SXHKD_SHELL=/usr/bin/bash

export PATH=$PATH:$BSPWM_DIR:$SCRIPTS_DIR

workspaces() {
  name=1
  for monitor in `bspc query -M`; do
    bspc monitor ${monitor} -n "$name" -d '󰅩' '' '' ''
    let name++
  done
}

workspaces

bspc config border_width         2
bspc config window_gap          12

# bspc config split_ratio          0.52
# bspc config borderless_monocle   true
# bspc config gapless_monocle      true

bspc config borderless_monocle true
bspc config gapless_monocle true
# bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config presel_feedback true

bspc rule -a Alacritty desktop='^1'
bspc rule -a Sidekick-browser desktop='^2'
bspc rule -a Thunar state=floating center=on
bspc rule -a Google-chrome desktop='^2'
bspc rule -a Slack       state=floating center=on
bspc rule -a 1Password   state=floating center=on
bspc rule -a Pavucontrol state=floating center=on


# ==== Autostart ====

kill -9 xfsettingsd xfce-power-manager
kill -9 $(pidof dunst)
kill -9 $(pidof picom)

if [[ ! `pidof xfce-polkit` ]]; then
  /usr/libexec/xfce-polkit &
fi

dunst -config $HOME/.config/bspwm/dunstrc &

pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/bspwm/sxhkdrc &

xfsettingsd &
xfce4-power-manager &
fehbg &
launch_polybar &
picom --config $BSPWM_DIR/picom.conf &
