-- return {
--   "stevearc/conform.nvim",
--   opts = {
--     formatters_by_ft = {
--       lua = { "stylua" },
--       javascript = { { "prettierd", "prettier" } },
--       -- ruby = { "solargraph" },
--       json = { "prettierd" },
--       cpp = { "cpplint" },
--     },
--     format_on_save = {
--       timeout_ms = 500,
--       lsp_format = "fallback",
--     },
--   },
-- }
return {}
